apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificaciones
  template:
    metadata:
      labels:
        app: notificaciones
    spec:
      containers:
        - name: notificaciones
          image: notificaciones:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: notificaciones
spec:
  type: ClusterIP
  selector:
    app: notificaciones
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
